### ISSUE TITLE
楼主 我用手动导入就是会出问题  总是会缺少文件 你能不能看看呢 

### ISSUE THREAD

**Issue by 1271918333** [hujewelz/HUPhotoBrowser#10]

**Comment by hujewelz** [comment]
README文件更新了哦，可以看看README，记得导入工程文件时也要把源码文件一起导入，让后正确添加 Header Search Paths

**Comment by 1271918333** [comment]
恩恩 好的 我还想请问下像相册查看照片下滑图片会一边下移一边缩小 放手之后回到原位 这个该怎么实现呢

**Comment by hujewelz** [comment]
添加手势，缩放图片


发自我的 iPhone

**Comment by 1271918333** [comment]
我添加了，但是会有问题，会影响左右滑动。


发自网易邮箱大师
在2017年03月20日 18:22，Jewelz Hu 写道：
添加手势，缩放图片


发自我的 iPhone

**Comment by hujewelz** [comment]
左右滑动使用swip,拖动使用pan

发自我的 iPhone

**Comment by 1271918333** [comment]
这个我实现了 我没有用手势 我就使用了imageView的transform，但是楼主你看见我刚提的那个问题了吗 就是放大的话会有问题

**Comment by hujewelz** [comment]
我测试过，没有问题，看看你是不是少了什么步骤


发自我的 iPhone
