### ISSUE TITLE
双击放大之后好像有点问题 没有适配图片和屏幕  小图片的话会滑到屏幕外面   有的时候滑着滑着就突然恢复了。

### ISSUE THREAD

**Issue by 1271918333** [hujewelz/HUPhotoBrowser#11]

**Comment by 1271918333** [comment]
我还有个问题想请教你 就是长图怎么点击了之后显示一个全屏的大图 然后可以向下滑动查看呢

**Comment by hujewelz** [comment]
把imageview放到scrollview中

**Comment by 1271918333** [comment]
你的好像就是添加在scrollView上的，楼主你还有空再看看放大那块吗

**Comment by hujewelz** [comment]
一般的图片缩放都是通过scrollview的zoom方法实现的哦，不知道你有什么其他的想法没？

发自我的 iPhone

**Comment by 1271918333** [comment]
我就是一个菜鸟 不过我有找别人的算法跟你的作比较 但是改了之后会有点问题 而且我不知道咋改 所以想问问你看看
