### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Yacong** [hujewelz/HUPhotoBrowser#4]
点击大图，然后滑动大图到原先小图cell没有显示的图片，点击返回，不会滚动到对应的小图cell和dissmiss动画也无法完成（小图cell重用问题）

**Comment by hujewelz** [comment]
主要是在内部无法获取到所有图片所在的视图，也就不能完成你所说的功能。如果在初始化传入所有图片所在的视图，并不是明智的选择，所以不能完成dismiss动画。对于滚动到对应的小图，因为并不能确定图片ImageView所在的父视图，所有并没有一个统一的方法完成滚动到对于小图的功能。如果你有什么好的想法，欢迎fork

**Comment by Yacong** [comment]
是的，之前做过的图片浏览器也是这个原因，导致后来就只能放弃这个功能。不过看到系统的相册可以这样做，只能想想其它方式

**Comment by hujewelz** [comment]
嗯，对单一的视图，比如collectionview，tableview是可以的，作为第三方的话，你不能确定别人使用的是什么视图，所以就无法实现想要的效果。我有时间再研究研究
