### ISSUE TITLE
手动导入，运行崩溃

### ISSUE THREAD

**Issue by WoNiu361** [hujewelz/HUPhotoBrowser#7]
不用CocoaPods管理这个库，而是下载新的，手动导入，按照事例代码操作，我创建UICollectionView，点击时会崩溃，不知道您发现没有？

**Comment by hujewelz** [comment]
嗯，好的，非常感谢。我试试哈。

发自我的 iPhone

**Comment by hujewelz** [comment]
能看一下您的报错信息吗
